package de.ativelox.feo.client.model.gfx;

/**
 * @author Ativelox ({@literal ativelox.dev@web.de})
 *
 */
public enum EResource {

    TILESET_FIELDS, MAP, MENU_BACKGROUND, MENU_BUTTON, DIALOGUE_FONT, REGULAR_FONT, SYSTEM_SELECTOR_LEFT,
    SYSTEM_SELECTOR_RIGHT, MAP_MOVE_LEFT, MAP_MOVE_RIGHT, MAP_MOVE_UP, MAP_MOVE_DOWN, MAP_HOVER, MAP_SELECTION,
    MAP_SELECTOR, MAP_INDICATOR, ACTION_WINDOW_MIDDLE, ACTION_WINDOW_TOP, ACTION_WINDOW_BOTTOM, ACTION_SELECTOR,
    PORTRAIT, BURST_WINDOW, TILE_STATUS, PALETTE, TARGET_SELECTOR, BATTLE_PREVIEW, BATTLE_PLATFORM_WIDE,
    BATTLE_PLATFORM_CLOSE, BATTLE_BACKGROUND, BATTLE_ANIMATION, HP_BAR_EMPTY, HP_BAR_FULL, HP_BAR_TRAILING, MUSIC, SFX,
    WEAPON_IMAGE, DIALOGUE_MAIN, DIALOGUE_CONTINUE;

}
