package de.ativelox.feo.client.model.sound;

/**
 * @author Ativelox ({@literal ativelox.dev@web.de})
 *
 */
public enum EMusic {

    AFTER_THE_WAR, AN_UNEXPECTED_CALLER, ARENA_BATTLE, ARENA_ENTRANCE, AT_THE_FINAL_DRAGON, ATTACK, BATTLE_FOR_TOMORROW,
    BATTLE_FOR_WHOM, BATTLE_RESULTS, BEHOLDING_NATURES_BEAUTY, BENEATH_A_NEW_LIGHT, BEYOND_THE_SKY, BGM, BINDING_TIES,
    CAMPAIGN, CAPTIVATING_DANCE, COGS_OF_FATE, CURING, DEER_OF_THE_PLAINS, DIGNIFIED, DISTANT_LANDS, DISTANT_UTOPIDA,
    DRAGON_SANCTUARY, EPILOGUE, ETERNAL_WIND, FE_GAIDEN_ENEMY_PHASE, FE_GAIDEN_PLAYER_PHASE, FINAL_CHAPTER,
    FINAL_FAREWELL, FIRE_EMBLEM_THEME, GAME_OVER, GOING_MY_WAY, HAPPINESS_ABOUNDS, HEALING, IN_THE_NAME_OF_BERN,
    INTO_THE_SHADOW_OF_TRIUMPH, INVISIBLE_ENEMY, JOIN_US, LEGENDARY_INHERITANCE, MAIN_THEME_ARRANGEMENT, MELANCHOLIC,
    MESSENGER_FROM_THE_DARKNESS, ONE_WILL, POEM_OF_THE_SOFT_WIND, PRELUDE_TELLING_A_LEGEND, PREPARE_TO_CHARGE,
    PRIESTESS_IN_THE_DARK, PRINCESS_OF_DESTINY, RECAPTURING_THE_ROYAL_CAPITAL, REVENGE, SCARS_OF_THE_SCOURING,
    SHADOW_APPROACHES, SHOCKING_TRUTH_I, SHOCKING_TRUTH_II, SHOP, SUSPICIOUS, TALKING, THE_DARK_PRIESTESS,
    THE_KING_OF_BERN, THE_KINGDOM_OF_BERN, THE_PATH_TO_GREATNESS, TO_THE_HEIGHTS, TRIUMPH, WHAT_CAME_BEFORE,
    WHEN_THE_RUSH_COMES, WILD_FRONTIER, WINNING_ROAD;

}
